version: '3.8'

services:
  marimo:
    env_file: .env
    build:
      context: ide/
      dockerfile: Dockerfile
    ports:
      - "2718:2718"
    volumes:
      - ${PWD}:${PWD}  # Use absolute path of current directory
      - ${PWD}/helpers:${PWD}/helpers  # Mount helpers with absolute path
      - marimo-cache:/root/.cache/marimo    
    environment:
      - PYTHONPATH=${PWD}:${PWD}/helpers  # Add helpers to Python path
      - MARIMO_NO_ANALYTICS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2718"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cosmic-network

  dashboard-frontend:
    env_file: 
      - .env
      - .env.local
    build:
      context: dashboard/frontend/
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_MARIMO_URL=http://localhost:2718
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cosmic-network

  dashboard-backend:
    env_file: 
      - .env
    volumes:
      - ${PWD}/dashboard/backend:/app/backend  # Use absolute path of current directory
      - ${PWD}/helpers:/app/helpers  # Mount helpers with absolute path
    build:
      context: dashboard/backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: /bin/sh -c "sleep infinity"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cosmic-network

volumes:
  marimo-cache:

networks:
  cosmic-network:
    driver: bridge
