version: '3.8'

services:
  marimo:
    env_file: .env
    build:
      context: ide/
      dockerfile: Dockerfile
    ports:
      - "2718:2718"
    volumes:
      - ${PWD}/ide:/app
      - ${PWD}/helpers:/app/helpers  # Mount helpers with absolute path
    environment:
      - PYTHONPATH=/app:/app/helpers  # Fixed: Changed /ide to /app
      - MARIMO_NO_ANALYTICS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2718"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cosmic-network

  dashboard-frontend:
    env_file: 
      - .env
      - .env.local
    build:
      context: dashboard/frontend/
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_MARIMO_URL=http://localhost:2718
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard/frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cosmic-network
    # depends_on:
      # dashboard-backend:
      #   condition: service_healthy
      # marimo:
      #   condition: service_healthy
      
  dashboard-backend:
    env_file: 
      - .env
    volumes:
      - ${PWD}/dashboard/backend:/app  # Use absolute path of current directory
      - ${PWD}/helpers:/app/helpers  # Mount helpers with absolute path
      - /var/run/docker.sock:/var/run/docker.sock:ro
    build:
      context: dashboard/backend/
      dockerfile: Dockerfile
    ports:
      - "47153:47153"
    # command: /bin/sh -c "sleep infinity"
    healthcheck:
      test: ["CMD", "wscat", "-c", "ws://localhost:47153/ws/test/test"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cosmic-network

# volumes:
  # ide-cache:

networks:
  cosmic-network:
    driver: bridge
