version: '3.8'

services:
  marimo:
    env_file: .env
    build:
      context: ide/
      dockerfile: Dockerfile
    ports:
      - "2718:2718"
    volumes:
      - ${PWD}/helpers:/helpers  # Mount helpers with absolute path
    environment:
      - PYTHONPATH=/ide:/helpers  # Add helpers to Python path
      - MARIMO_NO_ANALYTICS=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2718"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cosmic-network

  dashboard-frontend:
    env_file: 
      - .env
      - .env.local
    build:
      context: dashboard/frontend/
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_MARIMO_URL=http://localhost:2718
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard/frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cosmic-network
      
  dashboard-backend:
    env_file: 
      - .env
    volumes:
      - ${PWD}/dashboard/backend:/app  # Use absolute path of current directory
      - ${PWD}/helpers:/app/helpers  # Mount helpers with absolute path
    build:
      context: dashboard/backend/
      dockerfile: Dockerfile
    ports:
      - "47153:47153"
    # command: /bin/sh -c "sleep infinity"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:47153"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cosmic-network

volumes:
  marimo-cache:

networks:
  cosmic-network:
    driver: bridge
